version: '3.1'

networks:
  crudzin:
    driver: bridge

volumes:
  crudzindb:

services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: golang-crud
    volumes:
      - crudzin:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT_EXPOSE}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - crudzin