version: '3'
networks:
  db:
    driver: bridge
services:
  postgres:
      image: postgres:alpine
      networks:
        - db
      restart: always
      container_name: golang-crud
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - ${POSTGRES_PORT_EXPOSE}:${POSTGRES_PORT}